### ISSUE TITLE
Wallpaper is spelled wrong on this line.

### ISSUE THREAD

**Issue by wi-ry** [Sauler/WallpaperSync#3]
https://github.com/Sauler/WallpaperSync/blob/f369c8b640f8b2629b7079c79d5c68a46cce42e0/WallpaperSync.ps1#L34

**Comment by Sauler** [comment]
Fixed in commit [0b8662e89684330bbad86ad3ca696442d2d35dbb](https://github.com/Sauler/WallpaperSync/commit/0b8662e89684330bbad86ad3ca696442d2d35dbb)
